from .asset_cache import DerivedAssetCache, DerivedAssetCacheDiagnostics
from .asset_optimization import (
    MeshOptimizationResult,
    TextureOptimizationResult,
    optimize_mesh_data,
    optimize_texture_bytes,
    register_texture_optimizer,
)
from .asset_pipeline import (
    AssetDependencyGraph,
    AssetFingerprint,
    AssetImportDiagnostics,
    AssetImportRequest,
    AssetImportResult,
    AssetImportState,
    AssetPipeline,
)
from .assets import AssetDiagnostics, AssetInfo, AssetManager, AssetReloadResult
from .audio import AudioBackend, AudioEngine, AudioHandle, AudioReloadEvent, PygameAudioBackend
from .character import (
    CharacterActionBindings3D,
    CharacterConfig3D,
    CharacterController3D,
    CharacterDiagnostics3D,
    CharacterInput3D,
    CharacterNavigationDriver3D,
    CharacterState3D,
    FirstPersonController3D,
    PlatformerController3D,
    ThirdPersonController3D,
    follow_character_path,
)
from .core.events import EventBus
from .core.game import Game
from .core.scene import Scene, SceneDiagnostics, SceneMount
from .debug import DebugOverlay
from .ecs import ECSDiagnostics, ECSWorld, Entity
from .editor import (
    HierarchyEdit,
    HierarchyItem,
    InspectorField,
    InspectorSnapshot,
    PropertyEdit,
    SceneInspector,
)
from .editor_assets import (
    EditorAssetBrowser,
    EditorAssetBrowserFrame,
    EditorAssetEntry,
    classify_editor_asset,
)
from .editor_diagnostics import (
    EditorConsole,
    EditorConsoleEntry,
    EditorConsoleFrame,
    EditorProfiler,
    EditorProfilerFrame,
)
from .editor_frontend import (
    EditorFrontendController,
    EditorFrontendFrame,
    FrontendHierarchyRow,
    FrontendInspectorRow,
    TkEditorApp,
    launch_editor,
    parse_editor_value,
)
from .editor_gizmo import EditorTransformGizmo, GizmoApplyResult, GizmoTransformSnapshot
from .editor_preview import (
    EditorPreviewFrame,
    EditorPreviewSession,
    EditorViewportImage,
    RendererViewportBridge,
)
from .editor_runtime import EditorRuntimeFrame, EditorRuntimeMode, EditorRuntimeSession
from .editor_state import (
    EDITOR_HIERARCHY_FORMAT,
    EDITOR_HIERARCHY_VERSION,
    EditorHierarchyNode,
    EditorHierarchyState,
    EditorTargetRef,
    capture_editor_hierarchy,
    restore_editor_hierarchy,
)
from .editor_viewport import EditorViewportController, ViewportPick, ViewportRay
from .editor_workspace import (
    EDITOR_PROJECT_FORMAT,
    EDITOR_PROJECT_VERSION,
    EditorPanelState,
    EditorProjectState,
    EditorSceneState,
    EditorShellFrame,
    EditorViewportState,
    EditorWorkspace,
    default_editor_panels,
)
from .exporting import (
    ExportPlan,
    ExportResult,
    ExportTarget,
    NativeBuildError,
    NativeBuildResult,
    PackagingProfile,
    ProjectExporter,
)
from .filewatch import FileChangeEvent, PluginAutoReloader, PollingFileWatcher, ReloadResult
from .gpu_particles import (
    GPUParticleBlendMode,
    GPUParticleDiagnostics,
    GPUParticleEmissionShape3D,
    GPUParticleEmitter3D,
    GPUParticleFrame,
    GPUParticleRenderMode3D,
)
from .graphics.accelerated_renderer2 import SceneAcceleratedRenderer2
from .graphics.animation import AnimatedSprite2D, AnimationClip, SpriteSheet, animated_sprite
from .graphics.camera import Camera2D
from .graphics.camera3d import Camera3D
from .graphics.csm_renderer import Renderer2
from .graphics.cubemap import (
    CubemapFaces,
    CubemapGPUTexture,
    CubemapImageData,
    ImageBasedEnvironment3D,
    cubemap_asset_paths,
    load_cubemap_faces,
    upload_cubemap,
)
from .graphics.environment import Environment3D, EnvironmentInstallation, Skybox3D, skybox_mesh_data
from .graphics.gltf import GltfSceneMesh, load_gltf, load_gltf_scene
from .graphics.gltf_asset import GltfPrimitiveAsset, load_gltf_material, load_gltf_primitives
from .graphics.gltf_dependencies import gltf_asset_dependencies
from .graphics.gltf_pipeline import register_gltf_asset_processor
from .graphics.hiz import HiZDepthPyramid3D, HiZQueryDiagnostics3D
from .graphics.hiz_gpu import HiZPyramidPass3D
from .graphics.ibl_renderer import ImageBasedPostProcessRenderer
from .graphics.instancing import (
    Frustum3D,
    Instance3D,
    InstancedCube3D,
    InstancedMesh3D,
    InstancingDiagnostics,
    PreparedInstanceFrame,
)
from .graphics.lights import (
    MAX_DIRECTIONAL_LIGHTS,
    MAX_POINT_LIGHTS,
    MAX_SPOT_LIGHTS,
    DirectionalLight3D,
    LightSelection3D,
    PointLight3D,
    SpotLight3D,
    select_lights,
)
from .graphics.live_assets import GPUTextureInvalidation, RendererAssetBridge
from .graphics.material import Material3D
from .graphics.mesh import Mesh3D, MeshData, cube_mesh
from .graphics.obj import load_obj
from .graphics.postprocess import PostProcessRenderer, PostProcessSettings, ToneMapping
from .graphics.primitives import Cube3D, Rectangle2D, Sprite2D, Text2D
from .graphics.renderer2 import Decal3D, Renderer2Settings
from .graphics.shader_mesh import SURFACE_3D_TEMPLATE, ShaderMesh3D, shader_material_3d
from .graphics.shader_pipeline import (
    ShaderDiagnostics,
    ShaderHookPoint,
    ShaderMaterial3D,
    ShaderPipelineError,
    ShaderProgramCache,
    ShaderSafetyError,
    ShaderTemplate,
    ShaderVariantKey,
    ShaderVariantSpec,
    prepare_shader_variant,
)
from .graphics.stats import RendererStats
from .hotreload import (
    HotReloadSnapshot,
    HotReloadStateDomain,
    HotReloadStateError,
    HotReloadStateRegistry,
)
from .input import (
    GAMEPAD_AXES,
    GAMEPAD_BUTTONS,
    GamepadSnapshot,
    InputManager,
    apply_deadzone,
    normalize_gamepad_axis,
    normalize_gamepad_button,
)
from .live_development import LiveDevelopmentHub, LiveDevelopmentResult
from .math.types import Color, Transform, Vec2, Vec3
from .network_gameplay import (
    ConnectionState,
    GameplayMessage,
    GameplaySession,
    MessageKind,
    MessageRouter,
    NetworkDiagnostics,
    RPCError,
    RPCRegistry,
    RPCResult,
)
from .networking import (
    NetworkAddress,
    NetworkPacket,
    PacketStreamDecoder,
    TCPClient,
    TCPPeer,
    TCPServer,
)
from .particles import ParticleEmitter2D
from .physics.collision2d import AABB, BoxCollider2D, CollisionWorld2D
from .physics.collision3d import (
    AABB3D,
    BoxCollider3D,
    Collider3D,
    CollisionDiagnostics3D,
    CollisionWorld3D,
    RaycastHit3D,
    SphereBounds3D,
    SphereCollider3D,
)
from .physics.rigidbody2d import PhysicsWorld2D, RigidBody2D
from .physics.rigidbody3d import PhysicsWorld3D, RigidBody3D
from .plugins import PluginError, PluginInfo, PluginManager
from .prefab import Prefab, PrefabInstance, PrefabOverrides, PrefabSelector
from .profiler import FrameProfile, Profiler
from .scene_acceleration import (
    AcceleratedSceneView3D,
    SceneAccelerationDiagnostics3D,
    SceneAccelerationFrame3D,
    SceneAccelerationRuntime3D,
    disable_scene_acceleration,
    enable_scene_acceleration,
)
from .scene_visibility import (
    SceneVisibilityIndex3D,
    VisibilityAABB3D,
    VisibilityEntry3D,
    VisibilityQueryDiagnostics3D,
    VisibilityQueryResult3D,
    visibility_bounds_for,
)
from .serialization import SceneCodecRegistry, SceneSerializationError, SceneSerializer
from .storage import SaveStore
from .tilemap import TileMap2D
from .ui import UIButton, UILabel, UIManager, UIPanel, UIProgressBar
from .ui_layout import UIAnchor, UIContainer, UILayout, UILayoutDirection, place_control
from .ui_navigation import UIFocusManager

__all__ = [
    "AABB",
    "AABB3D",
    "EDITOR_HIERARCHY_FORMAT",
    "EDITOR_HIERARCHY_VERSION",
    "EDITOR_PROJECT_FORMAT",
    "EDITOR_PROJECT_VERSION",
    "GAMEPAD_AXES",
    "GAMEPAD_BUTTONS",
    "MAX_DIRECTIONAL_LIGHTS",
    "MAX_POINT_LIGHTS",
    "MAX_SPOT_LIGHTS",
    "SURFACE_3D_TEMPLATE",
    "AcceleratedSceneView3D",
    "AnimatedSprite2D",
    "AnimationClip",
    "AssetDependencyGraph",
    "AssetDiagnostics",
    "AssetFingerprint",
    "AssetImportDiagnostics",
    "AssetImportRequest",
    "AssetImportResult",
    "AssetImportState",
    "AssetInfo",
    "AssetManager",
    "AssetPipeline",
    "AssetReloadResult",
    "AudioBackend",
    "AudioEngine",
    "AudioHandle",
    "AudioReloadEvent",
    "BoxCollider2D",
    "BoxCollider3D",
    "Camera2D",
    "Camera3D",
    "CharacterActionBindings3D",
    "CharacterConfig3D",
    "CharacterController3D",
    "CharacterDiagnostics3D",
    "CharacterInput3D",
    "CharacterNavigationDriver3D",
    "CharacterState3D",
    "Collider3D",
    "CollisionDiagnostics3D",
    "CollisionWorld2D",
    "CollisionWorld3D",
    "Color",
    "ConnectionState",
    "Cube3D",
    "CubemapFaces",
    "CubemapGPUTexture",
    "CubemapImageData",
    "DebugOverlay",
    "Decal3D",
    "DerivedAssetCache",
    "DerivedAssetCacheDiagnostics",
    "DirectionalLight3D",
    "ECSDiagnostics",
    "ECSWorld",
    "EditorAssetBrowser",
    "EditorAssetBrowserFrame",
    "EditorAssetEntry",
    "EditorConsole",
    "EditorConsoleEntry",
    "EditorConsoleFrame",
    "EditorFrontendController",
    "EditorFrontendFrame",
    "EditorHierarchyNode",
    "EditorHierarchyState",
    "EditorPanelState",
    "EditorPreviewFrame",
    "EditorPreviewSession",
    "EditorProfiler",
    "EditorProfilerFrame",
    "EditorProjectState",
    "EditorRuntimeFrame",
    "EditorRuntimeMode",
    "EditorRuntimeSession",
    "EditorSceneState",
    "EditorShellFrame",
    "EditorTargetRef",
    "EditorTransformGizmo",
    "EditorViewportController",
    "EditorViewportImage",
    "EditorViewportState",
    "EditorWorkspace",
    "Entity",
    "Environment3D",
    "EnvironmentInstallation",
    "EventBus",
    "ExportPlan",
    "ExportResult",
    "ExportTarget",
    "FileChangeEvent",
    "FirstPersonController3D",
    "FrameProfile",
    "FrontendHierarchyRow",
    "FrontendInspectorRow",
    "Frustum3D",
    "GPUParticleBlendMode",
    "GPUParticleDiagnostics",
    "GPUParticleEmissionShape3D",
    "GPUParticleEmitter3D",
    "GPUParticleFrame",
    "GPUParticleRenderMode3D",
    "GPUTextureInvalidation",
    "Game",
    "GamepadSnapshot",
    "GameplayMessage",
    "GameplaySession",
    "GizmoApplyResult",
    "GizmoTransformSnapshot",
    "GltfPrimitiveAsset",
    "GltfSceneMesh",
    "HiZDepthPyramid3D",
    "HiZPyramidPass3D",
    "HiZQueryDiagnostics3D",
    "HierarchyEdit",
    "HierarchyItem",
    "HotReloadSnapshot",
    "HotReloadStateDomain",
    "HotReloadStateError",
    "HotReloadStateRegistry",
    "ImageBasedEnvironment3D",
    "ImageBasedPostProcessRenderer",
    "InputManager",
    "InspectorField",
    "InspectorSnapshot",
    "Instance3D",
    "InstancedCube3D",
    "InstancedMesh3D",
    "InstancingDiagnostics",
    "LightSelection3D",
    "LiveDevelopmentHub",
    "LiveDevelopmentResult",
    "Material3D",
    "Mesh3D",
    "MeshData",
    "MeshOptimizationResult",
    "MessageKind",
    "MessageRouter",
    "NativeBuildError",
    "NativeBuildResult",
    "NetworkAddress",
    "NetworkDiagnostics",
    "NetworkPacket",
    "PackagingProfile",
    "PacketStreamDecoder",
    "ParticleEmitter2D",
    "PhysicsWorld2D",
    "PhysicsWorld3D",
    "PlatformerController3D",
    "PluginAutoReloader",
    "PluginError",
    "PluginInfo",
    "PluginManager",
    "PointLight3D",
    "PollingFileWatcher",
    "PostProcessRenderer",
    "PostProcessSettings",
    "Prefab",
    "PrefabInstance",
    "PrefabOverrides",
    "PrefabSelector",
    "PreparedInstanceFrame",
    "Profiler",
    "ProjectExporter",
    "PropertyEdit",
    "PygameAudioBackend",
    "RPCError",
    "RPCRegistry",
    "RPCResult",
    "RaycastHit3D",
    "Rectangle2D",
    "ReloadResult",
    "Renderer2",
    "Renderer2Settings",
    "RendererAssetBridge",
    "RendererStats",
    "RendererViewportBridge",
    "RigidBody2D",
    "RigidBody3D",
    "SaveStore",
    "Scene",
    "SceneAcceleratedRenderer2",
    "SceneAccelerationDiagnostics3D",
    "SceneAccelerationFrame3D",
    "SceneAccelerationRuntime3D",
    "SceneCodecRegistry",
    "SceneDiagnostics",
    "SceneInspector",
    "SceneMount",
    "SceneSerializationError",
    "SceneSerializer",
    "SceneVisibilityIndex3D",
    "ShaderDiagnostics",
    "ShaderHookPoint",
    "ShaderMaterial3D",
    "ShaderMesh3D",
    "ShaderPipelineError",
    "ShaderProgramCache",
    "ShaderSafetyError",
    "ShaderTemplate",
    "ShaderVariantKey",
    "ShaderVariantSpec",
    "Skybox3D",
    "SphereBounds3D",
    "SphereCollider3D",
    "SpotLight3D",
    "Sprite2D",
    "SpriteSheet",
    "TCPClient",
    "TCPPeer",
    "TCPServer",
    "Text2D",
    "TextureOptimizationResult",
    "ThirdPersonController3D",
    "TileMap2D",
    "TkEditorApp",
    "ToneMapping",
    "Transform",
    "UIAnchor",
    "UIButton",
    "UIContainer",
    "UIFocusManager",
    "UILabel",
    "UILayout",
    "UILayoutDirection",
    "UIManager",
    "UIPanel",
    "UIProgressBar",
    "Vec2",
    "Vec3",
    "ViewportPick",
    "ViewportRay",
    "VisibilityAABB3D",
    "VisibilityEntry3D",
    "VisibilityQueryDiagnostics3D",
    "VisibilityQueryResult3D",
    "animated_sprite",
    "apply_deadzone",
    "capture_editor_hierarchy",
    "classify_editor_asset",
    "cube_mesh",
    "cubemap_asset_paths",
    "default_editor_panels",
    "disable_scene_acceleration",
    "enable_scene_acceleration",
    "follow_character_path",
    "gltf_asset_dependencies",
    "launch_editor",
    "load_cubemap_faces",
    "load_gltf",
    "load_gltf_material",
    "load_gltf_primitives",
    "load_gltf_scene",
    "load_obj",
    "normalize_gamepad_axis",
    "normalize_gamepad_button",
    "optimize_mesh_data",
    "optimize_texture_bytes",
    "parse_editor_value",
    "place_control",
    "prepare_shader_variant",
    "register_gltf_asset_processor",
    "register_texture_optimizer",
    "restore_editor_hierarchy",
    "select_lights",
    "shader_material_3d",
    "skybox_mesh_data",
    "upload_cubemap",
    "visibility_bounds_for",
]

__version__ = "2.0.0"